site_name: Wen-Chieh Lee的生活 #your site name 顯示在左上角
site_url: https://wenchiehlee-life.github.io
site_author: 'Wen-Chieh Lee'
site_description: 'Wen-Chieh Lee life site'


repo_name: Mkdocs-life # 右上角的名字
repo_url: https://github.com/wenchiehlee/mkdocs-life # 右上角點選跳轉的連結
edit_uri: edit/main/docs # 編輯按鈕跳轉的連結
copyright: Copyright &copy; 2016 - 2024 Wen-Chieh Lee # 左下角的版權宣告

theme:
  name: 'material'
  custom_dir: docs/overrides #覆寫路徑
  favicon: assets/images/w.png # 網頁icon
  font: #谷歌字型，自行搜尋
    text: Noto Serif TC  # LXGW WenKai TC #文字字型
    code: Roboto Mono  #程式碼字型
  # logo: assets/favicon.png #左上角logo，可插入圖片連結
  icon:
    repo: fontawesome/brands/github #右上角圖示
    logo: logo
  palette:
    - scheme: default
      primary:  lime
      accent:  lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: zh-TW # 一些提示性的文字會變成中文
  features:
    - announce.dismiss #呈現可標記為由使用者讀取的臨時公告，可以包含一個用於取消當前公告的按鈕
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy #程式碼覆制
    # - content.code.select
    - content.tabs.link    
    - content.tooltips
    # - navigation.instant
    #- header.autohide  #自動隱藏
    - navigation.tracking #位址列中的 URL 將自動更新為在目錄中突出顯示的活動錨點
    - navigation.tabs #頂級部分將呈現在上面視口標題下方的選單層中，但在移動裝置上保持原樣
    # - navigation.prune
    # - navigation.tabs.sticky  #啟用粘性選項卡後，導航選項卡將鎖定在標題下方，並在向下滾動時始終保持可見
    - navigation.sections #啟用部分後，頂級部分在邊欄中呈現為1220px以上視口的組，但在移動裝置上保持原樣
    - navigation.top # 返回頂部的按鈕 在上滑時出現
    - navigation.footer #頁尾將呈現在邊欄中，但在移動裝置上保持原樣
    - navigation.expand # 開啟Tab時左側目錄全部展開
    - navigation.indexes #啟用節索引頁後，可以將文件直接附加到節
    - search.suggest # 搜尋輸入一些字母時推薦補全整個單詞
    - search.highlight # 搜尋出的文章關鍵詞加入高亮
    - search.share #搜尋分享按鈕    
    - toc.follow
    # - toc.integrate
plugins:  
  - blog: #部落格配置
      post_date_format: full #時間
      draft: true
      draft_if_future_date: true #自動將具有未來日期的帖子標記為草稿
      post_readtime: true
      post_readtime_words_per_minute: 265 #計算帖子的閱讀時間時讀者每分鐘預計閱讀的字數
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" #作者資訊
  - search: #搜尋配置
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-committers:
      enabled: !ENV [CI, false]
      repository: Wcowin/Mkdocs-Wcowin
      branch: main
      exclude:
        - index.md
        - tag.md
        - waline.md
        - blog/posts/update.md
        - blog/posts/wkw.md
        - about/link.md
  # - git-revision-date-localized:
  #     enabled: !ENV [CI, false]
  #     type: iso_date
  #     enable_creation_date: false
  #     exclude:
  #       - index.md
  #       - tag.md
  #       - liuyanban.md
  #       - blog/posts/update.md
  #       - blog/posts/wkw.md
  #       - about/link.md
  #       - websitebeauty/linktech.md
  - tags:
      tags_file: tag.md #分類標簽


extra:
  # alternate:
  #   - name: 簡體中文
  #     link: /
  #     # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #     lang: zh-TW   
  #   # - name: English
  #   #   link: /Mkdocs-Wcowin/en/
  #   #   # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #   #   lang: en
  #   # - name: China(TW)
  #   #   link: /Mkdocs-Wcowin/ZH-TW/
  #   #   # https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #   #   lang: zh-TW
  generator: true #是否刪除頁尾顯示“使用 MkDocs 材料製造”
  analytics:
    provider: google #谷歌分析
    property:

    # 網頁底部反饋
    feedback:
      title: 此頁面有幫助嗎？
      ratings:
        - icon: material/thumb-up-outline #圖示可自定義
          name: This page was helpful
          data: 1
          note: >-
            謝謝你的反饋！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wenchiehlee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wen-chieh-lee-8a242b50/
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=YdrASjsAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Wen-Chieh-Lee-4
    #- icon: simple/huggingface
    #  link: https://huggingface.co/wenchiehlee
    - icon: fontawesome/regular/envelope #聯系方式圖示
      link: mailto:<wenchiehlee1020@gmail.com> #郵件聯系方式
  # cookies設定（可選）
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我們也使用cookies來識別您的重覆訪問和偏好來衡量我們文件的有效性以及使用者是否找到他們要找的東西。
  #     如果你同意,你可以幫助我們讓我們的網站更好


markdown_extensions: #詳見https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支援Markdown檔案上方自定義標題標簽等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark

  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 程式碼塊高亮外掛
  - pymdownx.arithmatex: # latex支援
      generic: true
  - toc:
      permalink: true # 固定標題位置為當前位置
  - pymdownx.highlight: # 程式碼塊高亮
      anchor_linenums: true
      linenums: true # 顯示行號
      # auto_title: true # 顯示程式語言名稱
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

extra_javascript:
  # - javascripts/extra.js #自定義javascript
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
  - javascripts/mathjax.js #Latex支援
  - https://polyfill.io/v3/polyfill.min.js?features=es6 #Latex支援
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latex支援
  # - ckplayer/js/ckplayer.js #播放器配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支援
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了

extra_css:
  - stylesheets/extra.css # 自定義CSS
  - stylesheets/link.css #友鏈配置
  - stylesheets/customize.css # 搜尋圓角最佳化

  # - stylesheets/video.css #播放器可選配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支援
  # - ckplayer/css/ckplayer.css   #播放器配置
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支援
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支援

  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #字型
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字型
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字型
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字型
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.2.0/style.min.css
# Page tree
nav:
  # - 主頁: index.md
  - MKdocs中文教程:
      - MKdocs教程(三部曲):
          - 1. 利用mkdocs部署靜態網頁至GitHub pages: blog/Mkdocs/mkdocs1.md
          - 2. Mkdocs部署靜態網頁至GitHub pages配置說明(mkdocs.yml): blog/Mkdocs/mkdocs2.md
          - 3. 解決 mkdocs部署 Github Pages 自定義域名失效的問題: blog/Mkdocs/mkdocs3.md
      - Mkdocs美化:
          - 新增Mkdocs部落格: blog/Mkdocs/mkdocsblog.md
          - 網頁圓角化設計: blog/websitebeauty/yuanjiaohua.md
          - 新增評論系統(giscus為例): blog/websitebeauty/mkcomments.md
          - 新增線上聊天: blog/websitebeauty/webtalknow.md
          - 新增友鏈: blog/websitebeauty/linktech.md
          - 新增頂部公告欄: blog/websitebeauty/header.md
          - 修改網站字型: blog/websitebeauty/mkdocsfont.md
          - JS實現滑鼠樣式: blog/websitebeauty/shubiao.md
          - 背景特效: blog/websitebeauty/backgroud.md
          - 新增404頁面: blog/websitebeauty/404.md
          - 為MKdocs新增文章修訂時間戳: blog/websitebeauty/time.md
  - 建設MKdocs技能指北:
      - Markdown:
          - Markdown指南: develop/Markdown/markdown.md
          - MWeb Pro: develop/Markdown/MWeb.md
      - Git 實用技巧: develop/git.md
      - 利用Lighthouse測試網站效能: develop/lighthouse.md
      - 如何將 github pages 遷移到 vercel 上託管: develop/vercel.md
      - 設計美學:
          - 唐·諾曼—情感設計的三個層次: develop/designbeauty/db1.md
          - 我對設計的一些觀點: develop/designbeauty/my-to-desihn.md

  - 標簽: tag.md
  - 留言板: liuyanban.md
  - Blogger:
      - index: blog/index.md
  - 友鏈:
      - 友鏈: about/link.md
  - 關於:
      - 作者個人簡介: about/geren.md
      - 功能測試: about/test.md
  - 使用本主題: https://github.com/new?template_name=Mkdocs-Wcowin&templa