authors:
  wenchiehlee:
    name: Wen-Chieh Lee
    description: Senior Software Architect
    avatar: https://github.com/wenchiehlee.png
  andylee-me:
    name: Andy Lee
    description: AI Developer
    avatar: https://github.com/andylee-me.png
  kohsin520:
    name: Kohsin Lee
    description: Software/AI Developer
    avatar: https://github.com/kohsin520.png